name: Deploy to Github Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch: { }
jobs:
  esbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm install
    - run: npm run asbuild:release
    - name: Move files
      run: |
        mkdir public
        mv index.html build public/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
